### PR TITLE
stop using react internal transition events

### PR DESCRIPTION
**Pull request by cescoferraro**
solves #150

### CODE REVIEW

**Comment by diegoddox** [comment]
Thanks!

**Comment by reergymerej** [comment]
What version was this released in?  It's not mentioned in the changelog, but I know it's _after_ 4.4.6.

**Comment by diegoddox** [comment]
@reergymerej sorry but I'm not sure.

**Comment by reergymerej** [comment]
Thanks, @diegoddox.  I got lazy and just pulled the latest.

**Pull request merged**
