### PR TITLE
Add support for redux 5 and react-redux 9

### LINKED ISSUE #289: Add support for redux 5 and react-redux 9
It would be good if react-redux-toastr could get support for redux 5 and react-redux 9.

### PR DESCRIPTION
**Pull request by printfn**
From what I can tell there don't seem to be any changes necessary to make this library work with the new redux version, so this PR just updates the peer dependencies.

Close #289

### CODE REVIEW

**Review by yanghoxom — APPROVED** [review]

**Comment by yanghoxom** [comment]
I glad to see this, someone can review it?

**Review by diegoddox — APPROVED** [review]

**Comment by yanghoxom** [comment]
@printfn @diegoddox 
Did it work for you?
I tried with react-redux 9.1.0
it still throw this issue (same with before that)
image

```
ReduxToastr.js:179 Uncaught TypeError: (0 , _reactRedux.connect) is not a function
    at ../node_modules/react-redux-toastr/lib/ReduxToastr.js (ReduxToastr.js:179:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
    at fn (hot module replacement:61:1)
    at ../node_modules/react-redux-toastr/lib/index.js (index.js:8:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
    at fn (hot module replacement:61:1)
    at ./src/reducer.js (i18n.js:58:1)
    at options.factory (react refresh:6:1)
```

**Comment by printfn** [comment]
It works for me, although I use vite/esbuild instead of webpack.

**Comment by diegoddox** [comment]
It works for me as well, webpack setup, have you try to remove the node_modules and reinstall?

**Comment by yanghoxom** [comment]
@diegoddox I tried, I remove node_modules and reinstall and I also check inside node_modules to make sure I get 8.0.0 version, using react-redux 9.1 and redux 5.0.1
I had to downgrade to react-redux 8 for it to work

**Comment by jimbglenn** [comment]
I had this problem with react-redux 9.1 as well. Downgrading to 8 fixed it.

**Pull request merged**
