### PR TITLE
Makes it possible to close and add a callback when clicking the toastr

### LINKED ISSUE #194: Feature request: close toastr on clicking
Some users have habit to close a toastr by clicking it (not only through the close button, but also the entire toastr div), it will be kind to support this feature.

### PR DESCRIPTION
**Pull request by hugobessa**
* creates the new options check and callbacks in the ToastrBox
* renames handleClick to handleClickCloseButton to clarify
* adds the prop in ReduxToastr
* updates documentation

fixes #194

### CODE REVIEW

**Comment by diegoddox** [comment]
Thanks @hugobessa will take a look asap

**Comment by hugobessa** [comment]
Thanks, @diegoddox! If you think on some way to improve this feel free to reach me.

**Comment by diegoddox** [comment]
Thanks, there is some small things to be changed but I can do it <3

**Comment by bmoquist** [comment]
Adding the ability to click on a toastr with a callback is great. Regarding the closing behavior mentioned in #165 response, it still doesn't work well when using toastrActions.add. 

Setting ```closeOnToastrClick=true```, the toastr doesn't close immediately when the user clicks on the toastr --- only after the user's mouse exits the toastr (following the click). This is a confusing behavior for the user. The toastr still needs to be explicitly closed in a callback (either onCloseButtonClick or onToastrClick) to be closed immediately. 

No need to reopen #165 as this was not exactly the original poster's issue.

**Pull request merged**
