### PR TITLE
Rename file extension of jsx files from .js to .jsx.

### PR DESCRIPTION
**Pull request by nphmuller**
Modern tooling like https://vitejs.dev/guide/features.html#jsx, https://esbuild.github.io/content-types/#jsx and https://deno.land/manual@v1.30.3/advanced/jsx_dom/jsx use the file extension of the file detect if it should be treated as a plain javascript file or a jsx file. While this behaviour is customisable and it is possible to treat .js files as .jsx files, it's not good for the build performance and not recommended.

In our project react-redux-toastr was the only dependency left that uses .js files for JSX components. Would you be open to changing this? I made this MR to hopefully do as much of the work as possible.

### CODE REVIEW

**Comment by pierre-lebihan** [comment]
Up !
I got the same issue trying to set up Vite on our project !
Have you found a similar replacement toastr @nphmuller ?

**Review by diegoddox — APPROVED** [review]
LGTM

**Comment by diegoddox** [comment]
Will test and merge later on today, thanks for your contribution

**Comment by nphmuller** [comment]
Thank you! And thanks for maintaining this library!

**Comment by pierre-lebihan** [comment]
Thanks you ! :)

**Pull request merged**
