### PR TITLE
HTML option

### PR DESCRIPTION
**Pull request by vladimirbuskin**
Thank you for your job, any chance you can pull that additional "html" option?

### CODE REVIEW

**Comment by diegoddox** [comment]
@vladimirbuskin 
You need to pull the latest before create an PR and may I ask why you need this option?

**Comment by vladimirbuskin** [comment]
Ok, i need that to have ,BR tag processed, so far only for that, i want to show several separate errors or warnings withing one message, each starting from a new line. I tried /n and BR, then made that option.

**Comment by diegoddox** [comment]
Why not use the `message` method so?

**Comment by vladimirbuskin** [comment]
I like and i need error and warning styling
2 апр. 2016 г. 21:29 пользователь "Diego Oliveira" notifications@github.com
написал:

**Comment by diegoddox** [comment]
@vladimirbuskin You need to pull the latest and update the readme file

**Comment by diegoddox** [comment]
@vladimirbuskin I will close as I don't think is a good idea, I will implement a new version where you will be able to pass a `react` `component` for both `message` and `toastr` methods.

In this way it is up to the user if they wanna used `dangerouslysetinnerhtml`

**Comment by diegoddox** [comment]
@vladimirbuskin or you can implement that if you wish!

**Comment by diegoddox** [comment]
@vladimirbuskin I have implement so you can pass a options `component` by using this you can display what you want! hope that solve your problem.

**Comment by vladimirbuskin** [comment]
It is great, that was one of solutions i thought, much better than others,
thank you.
3 апр. 2016 г. 0:36 пользователь "Diego Oliveira" notifications@github.com
написал:

**Pull request closed without merging**
