### PR TITLE
Added a guard to prevent onCSSTransitionEnd from failing on null node

### PR DESCRIPTION
**Pull request by asselstine**

### CODE REVIEW

**Comment by diegoddox** [comment]
Thanks!

**Comment by asselstine** [comment]
Np @diegoddox.  Just waiting on the next release so that we can switch our package source back over to an official release... when you can ;)

**Comment by thomasMary** [comment]
Thanks @asselstine for the fix! @diegoddox would it be possible to publish a new npm version? Thanks

**Comment by diegoddox** [comment]
@asselstine @thomasMary done!

**Pull request merged**
