### PR TITLE
Add new react-redux v6 and upgrade development dependencies

### LINKED ISSUE #217: react-redux@6.0.0 is now out

### PR DESCRIPTION
**Pull request by EmrysMyrddin**
# Purpose

The goal of this PR is to to make `react-redux-toastr` usable with the new version of `react-redux` (currently v6.0.0).

# What have been done
While this only require to add the new version to the supported version in peer-dependencies, the development environment wasn't up to date. So i have upgraded to the latest versions of each libs and made the required changes.

### Replaced dependencies
During the upgrade, I had to remove `extract-text-webpack-plugin` since it doesn't support webpack v4. I replaced it with `mini-css-extract-plugin` which does pretty much the same thing.

### Removed dependencies 

I have also found that `jasmine`, `jshint` and `jshint-loader` wasn't used any where in the project, so I have removed them. Perhaps I have missed something... If it's the case, I will revert the commit.

### Fixes
 - __the project has now zero security vulnerability 🎉 **__
 - fixes  #217

---

This is my first contribution to this project, don't hesitate to tell me if I have done something wrong 🙂

### CODE REVIEW

**Comment by diegoddox** [comment]
@EmrysMyrddin LGTM <3

**Comment by EmrysMyrddin** [comment]
@diegoddox Thank's for the quick review :-)

Do you have an idea of when this will ships in a new release ?

**Comment by diegoddox** [comment]
I will do my best to do it today after work @EmrysMyrddin, and thank you very much for the PR <3

**Comment by EmrysMyrddin** [comment]
@diegoddox I'm not hurry, you have your time :-) It's juste to have an idea.

And your welcome ! My company is using your library on different projects, it's normal to give back some hours of work.

**Pull request merged**
